name: libghostty
description: Dart FFI bindings to libghostty-vt â€” the virtual terminal emulator library from Ghostty.
version: 0.0.1-dev.1
resolution: workspace

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  test: ^1.25.6
