name: libghostty
description: Dart FFI bindings to libghostty-vt, the VT emulator library from Ghostty.
version: 0.0.1-dev.1
repository: https://github.com/elias8/libghostty/packages/libghostty
resolution: workspace

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - terminal
  - emulator
  - ffi
  - ghostty
  - libghostty

environment:
  sdk: ^3.11.0

dependencies:
  code_assets: ^1.0.0
  crypto: ^3.0.6
  ffi: ^2.1.0
  hooks: ^1.0.0
  meta: ^1.16.0
  web: ^1.1.0

dev_dependencies:
  ffigen: ^20.0.0
  path: ^1.8.0
  shelf: ^1.4.0
  shelf_static: ^1.1.0
  stream_channel: ^2.1.0
  test: ^1.25.6
